#!/bin/bash

DESABLED= false

case $1 in
  -t)
    echo -e "${BOLD}[+]${NC} cleaning files"
    cargo clean
    echo -e "${GREEN}[+]${NC} runnning tests"
    cargo test --target x86_64-LunerOS.json || echo -e -e "${RED}[<!>]${NC} ${BOLD}an error happened${NC}"
    exit
    ;;
  -b)
    echo -e "${BOLD}[+]${NC} cleaning files"
    cargo clean
    echo -e "${BOLD}[+]${NC} building tree"
    cargo build --target x86_64-LunerOS.json
    exit
    ;;
  -c)
    echo -e "${BOLD}[+]${NC} cleaning files"
    cargo clean
    exit
    ;;
  -e)
    echo -e "${BOLD}[+]${NC} extras are desabled"
    DESABLED= true
    ;;
  --tree)
    tree -L 3
    exit
    ;;
  --cat) 
    cat *
    echo -e "\n"
    exit
    ;;
esac

START_TIME=$SECONDS

clear

echo "${GREEN}$(toilet -f mono12 runner)${NC}"
echo "for LunerOS"

echo -e "${BOLD}[+]${NC} initng"
GREEN='\033[1;32m'
RED='\033[31m'
BOLD='\033[1m'
NC='\033[0m'

echo -e "${BOLD}[+]${NC} cleaning files"
cargo clean

echo -e "${BOLD}[+]${NC} building tree"
cargo build --target x86_64-LunerOS.json
if ! cargo build --target x86_64-LunerOS.json; then
    echo -e "${RED}[<!>]${NC} error: build failed"
    fahh
    exit 1
else
    echo -e "${GREEN}[+]${NC} seccess"
fi
echo -e "${BOLD}[+]${NC} making bootimage"
cargo bootimage

DURATION=$(( SECONDS - START_TIME ))
echo -e "${BOLD}[+]${NC} executed in $DURATION s"
sleep 0.1

echo -e '${BOLD}[+]${NC} running'
cargo run

if [[ $DESABLED ]]; then
    echo -e "${BOLD}[+]${NC} do you want to run a debug? [y/n] or clean [c] or test [t]"
    read debig
    if [ $debig == "y" ]; then  
        qemu-system-x86_64 -drive format=raw,file=target/x86_64-LunerOS/debug/bootimage-LunerOS.bin -d int,cpu_reset -no-reboot
        exit

    elif [ $debig == "c" ]; then
        cargo clean
        clear
        exit

    elif [ $debig == "t" ]; then  
        cargo clear
        cargo test
        exit
    else  
        echo -e "${BOLD}[+]${NC} ok :D"
        exit
    fi
fi